condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
match_block_trailing_comma = false
max_width = 120
normalize_comments = true
reorder_imports = true
spaces_around_ranges = true
tab_spaces = 2
trailing_comma = "Never"
use_small_heuristics = "Max"
use_try_shorthand = true
fn_args_density = "Compressed"
