# This rustfmt.toml format is used by a custom rustfmt-nightly program.
# To install this program, do this:
#
# ```
# export CFG_RELEASE_CHANNEL=nightly
# rustup run nightly cargo install --force \
#     --git https://github.com/chaaz/rustfmt
# ```
#
# To run e.g.:
#
# ```
# rustup run nightly rustfmt --write-mode=<whatever> src/main.rs
# ```

condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
match_block_trailing_comma = false
max_width = 120
normalize_comments = true
reorder_imports = true
spaces_around_ranges = true
tab_spaces = 2
trailing_comma = "Never"
use_small_heuristics = "Off"
use_try_shorthand = true
fn_args_density = "Compressed"
fn_args_indent_style = "Visual"

# These aren't actually used, but will someday maybe
[width_heuristics]
fn_call_width = 100
struct_lit_width = 50
struct_variant_width = 50
array_width = 100
chain_width = 100
single_line_if_else_max_width = 70
